// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.
//
// Field constraints below use the `ballerina/constraint` standard library so
// invalid payloads are rejected with 400 at request binding time, before any
// gRPC call is made (issue #344).
// If this file is regenerated, re-apply the `@constraint` annotations.

import ballerina/constraint;
import ballerina/http;

public type entities_search_body record {
    # Required if `kind.major` is not provided
    string id?;
    entitiessearch_kind kind?;
    string name?;
    @constraint:String {
        pattern: {
            value: re `(\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|[+-]\d{2}:?\d{2})?)?)?`,
            message: "Invalid created format, expected YYYY-MM-DD or RFC3339"
        }
    }
    string created?;
    @constraint:String {
        pattern: {
            value: re `(\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|[+-]\d{2}:?\d{2})?)?)?`,
            message: "Invalid terminated format, expected YYYY-MM-DD or RFC3339"
        }
    }
    string terminated?;
};

public type EntitiesEntityIdMetadataResponse record {
};

# Required if `id` is not provided
public type entitiessearch_kind record {
    # Required if `id` is not provided
    string major?;
    string minor?;
};

public type RecordStringidStringrelatedEntityIdStringnameStringstartTimeStringendTimeStringdirectionArrayOk record {|
    *http:Ok;
    record {string id?; string relatedEntityId?; string name?; string startTime?; string endTime?; string direction?;}[] body;
|};

public type InlineResponse2001Ok record {|
    *http:Ok;
    inline_response_200_1 body;
|};

public type inline_response_200_1 record {
    record {string id?; record {string major?; string minor?;} kind?; string name?; string created?; string terminated?;}[] body?;
};

public type inline_response_200 record {
    string[] body?;
};

public type attributes_attributeName_body record {
    # List of record filters to apply row base filtering
    record {
        @constraint:String {
            minLength: {value: 1, message: "records[].field_name is required"}
        }
        string field_name;
        "eq"|"neq"|"gt"|"lt"|"gte"|"lte"|"contains"|"notcontains" operator = "eq";
        string value?;
    }[] records?;
};

public type RecordStringStartStringendStringvalueRecordStringStartStringendStringvalueArrayOk record {|
    *http:Ok;
    record {string 'start?; string end?; string value?;}|record {string 'start?; string end?; string value?;}[] body;
|};

# Filter criteria for relations. Use either activeAt OR startTime/endTime, but not both. If no time filters are provided, all relations will be returned.
public type entityId_relations_body record {
    # Optional relation ID filter
    string id?;
    # Optional related entity ID filter
    string relatedEntityId?;
    # Optional relation name filter
    string name?;
    # Filter relations active at this specific time
    @constraint:String {
        pattern: {
            value: re `(\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|[+-]\d{2}:?\d{2})?)?)?`,
            message: "Invalid activeAt format, expected YYYY-MM-DD or RFC3339"
        }
    }
    string activeAt?;
    # Filter relations with start time
    @constraint:String {
        pattern: {
            value: re `(\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|[+-]\d{2}:?\d{2})?)?)?`,
            message: "Invalid startTime format, expected YYYY-MM-DD or RFC3339"
        }
    }
    string startTime?;
    # Filter relations with end time
    @constraint:String {
        pattern: {
            value: re `(\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?(\.\d+)?(Z|[+-]\d{2}:?\d{2})?)?)?`,
            message: "Invalid endTime format, expected YYYY-MM-DD or RFC3339"
        }
    }
    string endTime?;
    # Filter by relation direction
    @constraint:String {
        pattern: {value: re `(OUTGOING|INCOMING)`, message: "direction must be either OUTGOING or INCOMING"}
    }
    string direction?;
};
